/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2020-03-16 03:57:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.goods;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/theme.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("#footer {\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-top: 1px solid #ddd;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#topcontrol {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  z-index: 99;\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  background: #222;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  right: 14px !important;\r\n");
      out.write("  bottom: 11px !important;\r\n");
      out.write("  border-radius: 3px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topcontrol:after {\r\n");
      out.write("  /*top: -2px;*/\r\n");
      out.write("  left: 8.5px;\r\n");
      out.write("  content: \"\\f106\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: FontAwesome;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topcontrol:hover {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background: #18ba9b;\r\n");
      out.write("    -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write(".nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {\r\n");
      out.write("    border-bottom-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write(".nav-tabs>li>a {\r\n");
      out.write("    border-radius: 0;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write(" <div class=\"navbar-wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t\t  <div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t  <a class=\"navbar-brand\" href=\"index.html\" style=\"font-size:32px;\">超洁洗衣店洗衣平台</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            <div id=\"navbar\" class=\"navbar-collapse collapse\" style=\"float:right;\">\r\n");
      out.write("              <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                    <li><a href=\"member.html\"><i class=\"glyphicon glyphicon-scale\"></i> 会员中心</a></li>\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("                    <li class=\"divider\"></li>\r\n");
      out.write("                    <li><a href=\"index.html\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/cart\"><i class=\"glyphicon glyphicon-shopping-cart\"></i> 我的洗衣<span class=\"label label-danger\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${washcartnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container theme-showcase\" role=\"main\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <nav class=\"navbar navbar-default\" role=\"navigation\">                        \r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a rel=\"nofollow\" href=\"index.html\"><i class=\"glyphicon glyphicon-home\"></i> 首页</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li >\r\n");
      out.write("                                    <a rel=\"nofollow\" href=\"projects.html\"><i class=\"glyphicon glyphicon-th-large\"></i> 商品总览</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                           \r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div class=\"jumbotron nofollow\" style=\"    padding-top: 10px;\">\r\n");
      out.write("                        <h3>\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div style=\"float:left;width:70%;\">\r\n");
      out.write("                            ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.remark }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"float:right;\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default\"><i style=\"color:#f60\" class=\"glyphicon glyphicon-heart\"></i> 关注 111</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div class=\"row clearfix\">\r\n");
      out.write("                        <div class=\"col-md-8 column\">\r\n");
      out.write("                            <img alt=\"140x140\" width=\"740\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/goods/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.iconpath1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("            \r\n");
      out.write("                           \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 column\">\r\n");
      out.write("                            <div class=\"panel panel-default\" style=\"border-radius: 0px;\">\r\n");
      out.write("                                <div class=\"panel-heading\" style=\"background-color: #fff;border-color: #fff;\">\r\n");
      out.write("                                    <span class=\"label label-success\"><i class=\"glyphicon glyphicon-tag\"></i> 热卖中</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    <h3 >\r\n");
      out.write("                                        金额：￥<span style=\"color:red;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span>\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                     <p><span>已有629人购买该商品</p>\r\n");
      out.write("                                     <button type=\"button\" class=\"btn  btn-warning btn-lg btn-block\" data-toggle=\"modal\" data-target=\"#myModal\"><i class=\"glyphicon glyphicon-shopping-cart\"></i> 加入购物车</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-footer\" style=\"    background-color: #fff;\r\n");
      out.write("                                    border-top: 1px solid #ddd;\r\n");
      out.write("                                    border-bottom-right-radius: 0px;\r\n");
      out.write("                                    border-bottom-left-radius: 0px;\">\r\n");
      out.write("                                <div class=\"container-fluid\">\r\n");
      out.write("                                    <div class=\"row clearfix\">\r\n");
      out.write("                                        <div class=\"col-md-3 column\" style=\"padding:0;\">\r\n");
      out.write("                                <img alt=\"140x140\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/services-box2.jpg\" data-holder-rendered=\"true\" style=\"width: 80px; height: 80px;\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-9 column\">\r\n");
      out.write("                                    <div class=\"\">\r\n");
      out.write("                                        <h4>\r\n");
      out.write("                                            <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.sellerInfo.introduce }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</b> <span style=\"float:right;font-size:12px;\" class=\"label label-success\">已认证</span>\r\n");
      out.write("                                        </h4>\r\n");
      out.write("                                        <p style=\"font-size:12px\">\r\n");
      out.write("                                           ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.sellerInfo.remark }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                        <p style=\"font-size:12px\">\r\n");
      out.write("                                        客服电话:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.sellerInfo.cstel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\r\n");
      out.write("                                        </p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\t\t\t\t\t<div class=\" panel panel-default\" style=\"border-radius: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 >\r\n");
      out.write("\t\t\t\t\t\t\t\t风险提示\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("                            <p>互联网金融交易存在风险，基于买卖双方的自愿，请谨慎决定是否继续执行交易内容。</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div><h2>为你推荐</h2><hr></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"prjtip panel panel-default\" style=\"border-radius: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/product-3.png\" width=\"100%\" height=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<div class=\"prjtip panel panel-default\" style=\"border-radius: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/product-4.jpg\" width=\"100%\" height=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\" style=\"margin-top:20px;\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div id=\"footer\">\r\n");
      out.write("                        <div class=\"footerNav\">\r\n");
      out.write("                             <a rel=\"nofollow\" href=\"http://www.atguigu.com\">关于我们</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">服务条款</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">免责声明</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">网站地图</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">联系我们</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"copyRight\">\r\n");
      out.write("                            Copyright ?2010-2014atguigu.com 版权所有\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("    </div> <!-- /container -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" >\r\n");
      out.write("      <div class=\"modal-dialog \"  style=\"width:480px;height:220px;\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\" data-spy=\"scroll\" data-target=\"#myScrollspy\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("            <h4 class=\"modal-title\" id=\"myModalLabel\">请输入洗衣套餐预定数量</h4>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row clearfix\">\r\n");
      out.write("\t\t<div id=\"navList\" class=\"col-sm-9 col-md-9 column\" style=\"height:220px;overflow-y:auto;\">\r\n");
      out.write("            <h2 id=\"section-1\" style=\"border-bottom:1px dashed #ddd;\" ><span style=\"font-size:20px;font-weight:bold;\">￥");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.price }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span><span style=\"font-size:12px;margin-left:60px;\">剩余库存：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.stock }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</span></h2>\r\n");
      out.write("            <p>取送衣费用：</p>\r\n");
      out.write("            <p><input type=\"text\" id=\"buyCnt\" class=\"form-control\" style=\"width:100px;\"></p>\r\n");
      out.write("            <button type=\"button\" class=\"btn  btn-warning btn-lg \" >加入我的洗衣</button>\r\n");
      out.write("            <button type=\"button\" class=\"btn  btn-warning btn-lg \" onclick=\"goWashCart()\">加入后跳转购物车</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/back-to-top.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("    $(\".prjtip img\").css(\"cursor\", \"pointer\");\r\n");
      out.write("    $(\".prjtip img\").click(function(){\r\n");
      out.write("        window.location.href = 'project.html';\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function goWashCart(){\r\n");
      out.write("    \t$.ajax({\r\n");
      out.write("    \t\ttype : \"POST\",\r\n");
      out.write("    \t\turl  : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/addGoodsIntoWashCart\",\r\n");
      out.write("    \t\tdata : {\r\n");
      out.write("    \t\t\t\"gcategoryname\" : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.categoryname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("    \t\t\t\"gid\"           : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("    \t\t\t\"gname\"         : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("    \t\t\t\"cnt\"           : $(\" #buyCnt\").val(),\r\n");
      out.write("    \t\t\t\"gprice\"        : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${goods.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("    \t\t},\r\n");
      out.write("    \t\tsuccess : function(){\r\n");
      out.write("    \t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/cart\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("   \r\n");
      out.write("    \t});\r\n");
      out.write("    }\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
