/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2020-03-11 11:03:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.goodsCategory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class washindex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/userinfo.jsp", Long.valueOf(1582706783536L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/main.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.tree li {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\ttable tbody tr:nth-child(odd){background:#F4F4F4;}\r\n");
      out.write("\ttable tbody td:nth-child(even){color:#C00;}\r\n");
      out.write("    \r\n");
      out.write("    input[type=checkbox] {\r\n");
      out.write("        width:18px;\r\n");
      out.write("        height:18px;        \r\n");
      out.write("    }\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <div><a class=\"navbar-brand\" style=\"font-size:32px;\" href=\"#\">超洁洗衣店后台管理</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("            <li style=\"padding-top:8px;\">\r\n");
      out.write("\t\t\t\t");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t  <button type=\"button\" class=\"btn btn-default btn-success dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-cog\"></i> 个人设置</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/logout\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("\t\t\t\t\t  </ul>\r\n");
      out.write("\t\t\t    </div>");
      out.write("\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("            <li style=\"margin-left:10px;padding-top:8px;\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-danger\">\r\n");
      out.write("\t\t\t\t  <span class=\"glyphicon glyphicon-question-sign\"></span> 帮助\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <form class=\"navbar-form navbar-right\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" placeholder=\"Search...\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("\t\t\t<div class=\"tree\">\r\n");
      out.write("\t\t\t\t<ul style=\"padding-left:0px;\" class=\"list-group\">\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"main.html\"><i class=\"glyphicon glyphicon-dashboard\"></i> 控制面板</a> \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon glyphicon-tasks\"></i> 权限管理 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"user.html\"><i class=\"glyphicon glyphicon-user\"></i> 用户维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"role.html\"><i class=\"glyphicon glyphicon-king\"></i> 角色维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"permission.html\"><i class=\"glyphicon glyphicon-lock\"></i> 许可维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon-ok\"></i> 业务审核 <span class=\"badge\" style=\"float:right\">3</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;display:none;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_cert.html\"><i class=\"glyphicon glyphicon-check\"></i> 实名认证审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_adv.html\"><i class=\"glyphicon glyphicon-check\"></i> 广告审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"auth_project.html\"><i class=\"glyphicon glyphicon-check\"></i> 商品审核</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t<span><i class=\"glyphicon glyphicon-th-large\"></i> 业务管理 <span class=\"badge\" style=\"float:right\">7</span></span> \r\n");
      out.write("\t\t\t\t\t\t<ul style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/member\"><i class=\"glyphicon glyphicon-user\"></i> 用户维护</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/goodsCategory/washindex\" style=\"color:red;\"><i class=\"glyphicon glyphicon-equalizer\"></i> 分类管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"process.html\"><i class=\"glyphicon glyphicon-random\"></i> 流程管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"advertisement.html\"><i class=\"glyphicon glyphicon-hdd\"></i> 广告管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"message.html\"><i class=\"glyphicon glyphicon-comment\"></i> 消息模板</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/goodsCategory/index\"><i class=\"glyphicon glyphicon-list\"></i> 洗衣类型分类管理</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"tag.html\"><i class=\"glyphicon glyphicon-tags\"></i> 洗衣标签</a> \r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"list-group-item tree-closed\" >\r\n");
      out.write("\t\t\t\t\t\t<a href=\"param.html\"><i class=\"glyphicon glyphicon-list-alt\"></i> 参数管理</a> \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t  <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t<h3 class=\"panel-title\"><i class=\"glyphicon glyphicon-th\"></i> 数据矩阵</h3>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t  <div class=\"panel-body\">\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("          \r\n");
      out.write("           <div class=\"col-sm-9 col-md-9 column\">\r\n");
      out.write("              <ul id=\"myTab\" style=\"\" class=\"nav nav-pills\" role=\"tablist\">\r\n");
      out.write("                <li role=\"presentation\" class=\"active\"><a href=\"#home\" role=\"tab\" data-toggle=\"tab\" aria-controls=\"home\" aria-expanded=\"true\">我的洗衣店</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("              <div id=\"myTabContent\" class=\"tab-content\" style=\"margin-top:10px;\">\r\n");
      out.write("                  <div role=\"tabpanel\" class=\"tab-pane fade active in\" id=\"home\" aria-labelledby=\"home-tab\">\r\n");
      out.write("                  <form class=\"form-inline\" role=\"form\" style=\"float:left;\">\r\n");
      out.write("  <div class=\"form-group has-feedback\">\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <div class=\"input-group-addon\">查询条件</div>\r\n");
      out.write("      <input class=\"form-control has-success\" id=\"queryText\" type=\"text\" placeholder=\"请输入查询条件\">\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <button type=\"button\" class=\"btn btn-warning\" id=\"queryBtn\"><i class=\"glyphicon glyphicon-search\"></i> 查询</button>\r\n");
      out.write("</form>\r\n");
      out.write("                        <ul id=\"myTab1\" class=\"nav nav-tabs\">\r\n");
      out.write("                          \r\n");
      out.write("                            <li class=\" pull-right\">\r\n");
      out.write("                                 <button type=\"button\" class=\"btn btn-warning\" onclick=\"window.location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/addGoods'\"><i class=\"glyphicon glyphicon-plus\"></i>发布商品</button>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>                  \r\n");
      out.write("                        <div id=\"myTab1\" class=\"tab-content\" style=\"margin-top:10px;\">\r\n");
      out.write("                            <div role=\"tabpanel\" class=\"tab-pane fade active in\" id=\"support\" aria-labelledby=\"home-tab\">\r\n");
      out.write("                                <div class=\"container-fluid\">\r\n");
      out.write("                                    <div class=\"row clearfix\">\r\n");
      out.write("                                        <div  class=\"col-md-12 column\" style=\"margin-top:10px;padding:0;\">\r\n");
      out.write("                                            <table class=\"table table-bordered\" style=\"text-align:center;\" >\r\n");
      out.write("                                              <thead>\r\n");
      out.write("                                                <tr style=\"background-color:#ddd;\">\r\n");
      out.write("                                                  <td width=\"120\">洗衣类型</td>\r\n");
      out.write("                                                  <td width=\"120\">洗衣套餐信息</td>\r\n");
      out.write("                                                  <td width=\"120\">洗衣套餐编号</td>\r\n");
      out.write("                                                  <td width=\"120\">洗衣套餐图片</td>\r\n");
      out.write("                                                 \r\n");
      out.write("                                                  <td width=\"120\">金额（元）</td>\r\n");
      out.write("                                            \r\n");
      out.write("                                                  <td width=\"120\">库存数量</td>\r\n");
      out.write("                                                  <td width=\"120\">操作</td>\r\n");
      out.write("                                                </tr>\r\n");
      out.write("                                              </thead>\r\n");
      out.write("                                              <tbody id=\"goodsBody\">\r\n");
      out.write("                                               \r\n");
      out.write("                                              </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"attension\" aria-labelledby=\"attension-tab\">\r\n");
      out.write("                                <div class=\"container-fluid\">\r\n");
      out.write("                                    <div class=\"row clearfix\">\r\n");
      out.write("                                        <div class=\"col-md-12 column\" style=\"padding:0;\">\r\n");
      out.write("                                           \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                  \r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div role=\"tabpanel\" class=\"tab-pane fade\" id=\"profile\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("                  众筹资产\r\n");
      out.write("                  </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("        <div class=\"container\" style=\"margin-top:20px;\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div id=\"footer\">\r\n");
      out.write("                        <div class=\"footerNav\">\r\n");
      out.write("                             <a rel=\"nofollow\" href=\"http://www.atguigu.com\">关于我们</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">服务条款</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">免责声明</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">网站地图</a> | <a rel=\"nofollow\" href=\"http://www.atguigu.com\">联系我们</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"copyRight\">\r\n");
      out.write("                            Copyright ?2017-2017atguigu.com 版权所有\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/back-to-top.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layer/layer.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(function () {\r\n");
      out.write("\t\t\t    $(\".list-group-item\").click(function(){\r\n");
      out.write("\t\t\t\t    if ( $(this).find(\"ul\") ) {\r\n");
      out.write("\t\t\t\t\t\t$(this).toggleClass(\"tree-closed\");\r\n");
      out.write("\t\t\t\t\t\tif ( $(this).hasClass(\"tree-closed\") ) {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).hide(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"ul\", this).show(\"fast\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    var index = 0;\r\n");
      out.write("\t\t\t \t   $.ajax({\r\n");
      out.write("\t\t\t \t\t   type : \"POST\",\r\n");
      out.write("\t\t\t \t\t   url  : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/queryUserGoods\",\r\n");
      out.write("\t\t\t \t\t   beforeSend : function(){\r\n");
      out.write("\t\t\t \t\t\t   index = layer.load(2,{time:10*1000});\r\n");
      out.write("\t\t\t \t\t   },\r\n");
      out.write("\t\t\t \t\t   success : function(result){\r\n");
      out.write("\t\t\t \t\t\t   layer.close(index);\r\n");
      out.write("\t\t\t \t\t\t   if(result.success)\r\n");
      out.write("\t\t\t \t\t\t   {\r\n");
      out.write("\t\t\t \t\t\t\t   var goodsDatas = result.data;\r\n");
      out.write("\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t \t\t\t\t   var content = \"\";\r\n");
      out.write("\t\t\t \t\t\t\t    \r\n");
      out.write("\t\t\t \t\t\t\t   $.each(goodsDatas,function(i,goods){\r\n");
      out.write("\t\t\t \t\t\t\t\tcontent += '   <tr>                                                      ';\r\n");
      out.write("\t\t\t \t\t\t\t   content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t                     content += '         <span> '+goods.categoryname+' </span>                   ';\r\n");
      out.write("\t\t\t                     content += '   </td> ';\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t                     content += '         <span> '+goods.name+' </span>                   ';\r\n");
      out.write("\t\t\t                     content += '   </td>                                                     ';\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\">P001-001-001</td>      ';\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\"><img height=\"60\" width=\"60\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/goods/'+goods.iconpath+'\" /></td>              ';\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\">'+goods.price+'</td>              ';\r\n");
      out.write("\t\t\t               \r\n");
      out.write("\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\">'+goods.stock+'</td>            ';\r\n");
      out.write("\t\t\t                     content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t                     content += '     <div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical button group\"> ';\r\n");
      out.write("\t\t\t                     content += '           <button type=\"button\" onclick=\"window.location.href=\\'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/editWash?id='+goods.id+'\\'\" class=\"btn btn-info\"><i class=\"glyphicon glyphicon-pencil\"></i> 修改</button> ';\r\n");
      out.write("\t\t\t                     content += '           <button type=\"button\" onclick=\"deleteGood('+goods.id+',\\''+goods.name+'\\')\" class=\"btn btn-danger\"><i class=\"glyphicon glyphicon-remove\"></i> 删除</button> ';\r\n");
      out.write("\t\t\t                     content += '     </div>';\r\n");
      out.write("\t\t\t                     content += '   </td>';\r\n");
      out.write("\t\t\t                     content += '</tr> ';\r\n");
      out.write("\t\t\t \t\t\t\t   });\r\n");
      out.write("\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t \t\t\t\t   $(\"#goodsBody\").html(content);\r\n");
      out.write("\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t \t\t\t   } else {\r\n");
      out.write("\t\t\t \t\t\t\t\t layer.msg(\"商品信息查询失败!\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("\t\t\t                 \t\t //消息关闭后的逻辑\r\n");
      out.write("\t\t\t                 \t });\r\n");
      out.write("\t\t\t \t\t\t   }\r\n");
      out.write("\t\t\t \t\t   }\t  \r\n");
      out.write("            });\r\n");
      out.write("\t\t\t \t   \r\n");
      out.write("\r\n");
      out.write("\t\t\t \t  $(\"#queryBtn\").click(function(){\r\n");
      out.write("\t\t\t \t\t var jsonData = {};\r\n");
      out.write("\t\t\t\t    \tqueryText = $(\"#queryText\").val();\r\n");
      out.write("\t\t\t\t    \tif( queryText != \"\" ){\r\n");
      out.write("\t\t\t\t    \t\tlikeflag = true;\r\n");
      out.write("\t\t\t\t    \t\tjsonData.queryText = queryText;\r\n");
      out.write("\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t    \t var index = 0;\r\n");
      out.write("\t\t\t\t\t \t   $.ajax({\r\n");
      out.write("\t\t\t\t\t \t\t   type : \"POST\",\r\n");
      out.write("\t\t\t\t\t \t\t   url  : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/queryUserGoods\",\r\n");
      out.write("\t\t\t\t\t \t\t   data : jsonData,\r\n");
      out.write("\t\t\t\t\t \t\t   beforeSend : function(){\r\n");
      out.write("\t\t\t\t\t \t\t\t   index = layer.load(2,{time:10*1000});\r\n");
      out.write("\t\t\t\t\t \t\t   },\r\n");
      out.write("\t\t\t\t\t \t\t   success : function(result){\r\n");
      out.write("\t\t\t\t\t \t\t\t   layer.close(index);\r\n");
      out.write("\t\t\t\t\t \t\t\t   if(result.success)\r\n");
      out.write("\t\t\t\t\t \t\t\t   {\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   var goodsDatas = result.data;\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t\t\t \t\t\t\t   var content = \"\";\r\n");
      out.write("\t\t\t\t\t \t\t\t\t    \r\n");
      out.write("\t\t\t\t\t \t\t\t\t   $.each(goodsDatas,function(i,goods){\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\tcontent += '   <tr>                                                      ';\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t\t\t                     content += '         <span> '+goods.categoryname+' </span>                   ';\r\n");
      out.write("\t\t\t\t\t                     content += '   </td> ';\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t\t\t                     content += '         <span> '+goods.name+' </span>                   ';\r\n");
      out.write("\t\t\t\t\t                     content += '   </td>                                                     ';\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\">P001-001-001</td>      ';\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\"><img height=\"60\" width=\"60\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/img/goods/'+goods.iconpath+'\" /></td>              ';\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\">'+goods.price+'</td>              ';\r\n");
      out.write("\t\t\t\t\t               \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\">'+goods.stock+'</td>            ';\r\n");
      out.write("\t\t\t\t\t                     content += '   <td style=\"vertical-align:middle;\">                       ';\r\n");
      out.write("\t\t\t\t\t                     content += '     <div class=\"btn-group-vertical\" role=\"group\" aria-label=\"Vertical button group\"> ';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t                     content += '           <button type=\"button\" class=\"btn btn-info\"><i class=\"glyphicon glyphicon-pencil\"></i> 修改</button> ';\r\n");
      out.write("\t\t\t\t\t                     content += '           <button type=\"button\" class=\"btn btn-danger\"><i class=\"glyphicon glyphicon-remove\"></i> 删除</button> ';\r\n");
      out.write("\t\t\t\t\t                     content += '     </div>';\r\n");
      out.write("\t\t\t\t\t                     content += '   </td>';\r\n");
      out.write("\t\t\t\t\t                     content += '</tr> ';\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   });\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t\t\t \t\t\t\t   $(\"#goodsBody\").html(content);\r\n");
      out.write("\t\t\t\t\t \t\t\t\t   \r\n");
      out.write("\t\t\t\t\t \t\t\t   } else {\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\t layer.msg(\"商品信息查询失败!\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("\t\t\t\t\t                 \t\t //消息关闭后的逻辑\r\n");
      out.write("\t\t\t\t\t                 \t });\r\n");
      out.write("\t\t\t\t\t \t\t\t   }\r\n");
      out.write("\t\t\t\t\t \t\t   }\t  \r\n");
      out.write("\t\t            });\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t    })\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t \t   })\r\n");
      out.write("\t\t\t \t   \r\n");
      out.write("\t\t\tfunction deleteGood(id,name){\r\n");
      out.write("\t\t            \tlayer.confirm(\"删除该洗衣套餐信息【\"+name+\"】，是否继续？\",  {icon: 3, title:'提示'}, function(cindex){\r\n");
      out.write("\t\t    \t\t\t   var index = 0;\r\n");
      out.write("\t\t            \t\t$.ajax({\r\n");
      out.write("\t\t    \t\t\t    \ttype : \"POST\",\r\n");
      out.write("\t\t    \t\t\t    \turl  : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/user/deleteGood\",\r\n");
      out.write("\t\t    \t\t\t    \tdata : {\r\n");
      out.write("\t\t    \t\t\t    \t\t\"id\" : id\r\n");
      out.write("\t\t    \t\t\t    \t},\r\n");
      out.write("\t\t    \t\t\t    \tbeforeSend : function(){\r\n");
      out.write("\t\t    \t\t\t    \t\tindex = layer.load(2,{time: 10*1000});\r\n");
      out.write("\t\t    \t\t\t    \t},\r\n");
      out.write("\t\t    \t\t\t    \tsuccess : function(result) {\r\n");
      out.write("\t\t    \t\t\t    \t\tlayer.close(index);\r\n");
      out.write("\t\t    \t\t\t    \t\tif(result.success){\r\n");
      out.write("\t\t    \t\t\t    \t\t\t layer.msg(\"该洗衣套餐信息删除成功!\", {time:1500, icon:6, shift:6}, function(){\r\n");
      out.write("\t\t    \t\t                \t\t //消息关闭后的逻辑\r\n");
      out.write("\t\t    \t\t                \t\t$(\"#queryBtn\").click();\r\n");
      out.write("\t\t    \t\t                \t });\r\n");
      out.write("\t\t    \t\t\t    \t\t} else {\r\n");
      out.write("\t\t    \t\t       \t\t\t\t layer.msg(\"该洗衣套餐信息删除失败!\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("\t\t    \t\t                \t\t //消息关闭后的逻辑\r\n");
      out.write("\t\t    \t\t                \t\t\r\n");
      out.write("\t\t    \t\t                \t });\r\n");
      out.write("\t\t    \t\t\t    \t\t}\r\n");
      out.write("\t\t    \t\t\t    \t}\r\n");
      out.write("\t\t    \t\t\t    });\r\n");
      out.write("\t\t            \t\tlayer.close(cindex);\r\n");
      out.write("\t\t    \t\t\t}, function(cindex){\r\n");
      out.write("\t\t    \t\t\t    layer.close(cindex);\r\n");
      out.write("\t\t    \t\t\t});\r\n");
      out.write("\t\t    \t\t\t\r\n");
      out.write("\t\t            }\r\n");
      out.write("            \r\n");
      out.write("        </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
