/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2020-03-12 09:10:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addGoods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/memberinfo_1.jsp", Long.valueOf(1583891870812L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/theme.css\">\r\n");
      out.write("\t<style>\r\n");
      out.write("#footer {\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    border-top: 1px solid #ddd;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("#topcontrol {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  z-index: 99;\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  background: #222;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  right: 14px !important;\r\n");
      out.write("  bottom: 11px !important;\r\n");
      out.write("  border-radius: 3px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topcontrol:after {\r\n");
      out.write("  /*top: -2px;*/\r\n");
      out.write("  left: 8.5px;\r\n");
      out.write("  content: \"\\f106\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: FontAwesome;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#topcontrol:hover {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background: #18ba9b;\r\n");
      out.write("    -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".label-type, .label-status, .label-order {\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    color: #f60;\r\n");
      out.write("    padding : 5px;\r\n");
      out.write("    border: 1px #f60 solid;\r\n");
      out.write("}\r\n");
      out.write("#typeList  :not(:first-child) {\r\n");
      out.write("    margin-top:20px;\r\n");
      out.write("}\r\n");
      out.write(".label-txt {\r\n");
      out.write("    margin:10px 10px;\r\n");
      out.write("    border:1px solid #ddd;\r\n");
      out.write("    padding : 4px;\r\n");
      out.write("    font-size:14px;\r\n");
      out.write("}\r\n");
      out.write(".panel {\r\n");
      out.write("    border-radius:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".progress-bar-default {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\t</style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write(" <div class=\"navbar-wrapper\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("\t\t\t  <div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t  <a class=\"navbar-brand\" href=\"index.html\" style=\"font-size:32px;\">超洁洗衣店后台管理系统</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("            <div id=\"navbar\" class=\"navbar-collapse collapse\" style=\"float:right;\">\r\n");
      out.write("              <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                  <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"><i class=\"glyphicon glyphicon-user\"></i> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<span class=\"caret\"></span></a>\r\n");
      out.write("                  <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                    <li><a href=\"member.html\"><i class=\"glyphicon glyphicon-scale\"></i> 会员中心</a></li>\r\n");
      out.write("                    <li><a href=\"#\"><i class=\"glyphicon glyphicon-comment\"></i> 消息</a></li>\r\n");
      out.write("                    <li class=\"divider\"></li>\r\n");
      out.write("                    <li><a href=\"index.html\"><i class=\"glyphicon glyphicon-off\"></i> 退出系统</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/cart\"><i class=\"glyphicon glyphicon-shopping-cart\"></i> 购物车<span class=\"label label-danger\">42</span></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container theme-showcase\" role=\"main\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <nav class=\"navbar navbar-default\" role=\"navigation\">\r\n");
      out.write("                        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a rel=\"nofollow\" href=\"index.html\"><i class=\"glyphicon glyphicon-home\"></i> 首页</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li >\r\n");
      out.write("                                    <a rel=\"nofollow\" href=\"projects.html\"><i class=\"glyphicon glyphicon-th-large\"></i> 商品总览</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"active\">\r\n");
      out.write("                                    <a rel=\"nofollow\" href=\"javascript:;\"><i class=\"glyphicon glyphicon-edit\"></i> 发布商品</a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div class=\"panel panel-default\" >\r\n");
      out.write("                        <div class=\"panel-body\">\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row clearfix\">\r\n");
      out.write("\t\t<div class=\"col-md-12 column\">\r\n");
      out.write("\t\t\t<blockquote style=\"border-left: 5px solid #f60;color:#f60;padding: 0 0 0 20px;\">\r\n");
      out.write("\t\t\t\t<b>\r\n");
      out.write("\t\t\t\t\t商品及商家信息\r\n");
      out.write("\t\t\t\t</b>\r\n");
      out.write("\t\t\t</blockquote>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-12 column\">\r\n");
      out.write("\t\t\t<div class=\"page-header\" style=\"    border-bottom-style: dashed;\">\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t商品信息\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("            <form id=\"goodsForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/insertGood\" method=\"post\" enctype=\"multipart/form-data\" class=\"form-horizontal\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">分类信息</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">商品名称</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input name=\"name\" type=\"text\" class=\"form-control\" >\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">一句话简介</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <textarea name=\"remark\" class=\"form-control\" rows=\"5\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label  class=\"col-sm-2 control-label\">金额（元）</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input name=\"price\" type=\"text\" class=\"form-control\" style=\"width:100px;\" >\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">库存</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input name=\"stock\" type=\"text\" class=\"form-control\" value=\"0\" style=\"width:100px;\" >\r\n");
      out.write("                  <label class=\"control-label\">未设置，表示无限制</label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">商品头图</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <button id=\"headerImgBtn\" type=\"button\" class=\"btn btn-primary btn-lg active\">上传图片</button>\r\n");
      out.write("                  <input style=\"display:none;\" type=\"file\" name=\"goodsHeadImg\">\r\n");
      out.write("                  <label class=\"control-label\">图片上无文字,支持jpg、jpeg、png、gif格式，大小不超过2M，建议尺寸：740*457px</label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">商品详情</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <button id=\"imgBtn\" type=\"button\" class=\"btn btn-primary btn-lg active\">上传图片</button>\r\n");
      out.write("                   <input style=\"display:none;\" type=\"file\" name=\"goodsDetailImg\">\r\n");
      out.write("                  <label class=\"control-label\">支持jpg、jpeg、png、gif格式，大小不超过2M，建议尺寸：宽740px</label>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-12 column\">\r\n");
      out.write("\t\t\t<div class=\"page-header\" style=\"    border-bottom-style: dashed;\">\r\n");
      out.write("\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t商家信息\r\n");
      out.write("\t\t\t\t</h3>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">自我介绍</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" name=\"introduce\" class=\"form-control\" placeholder=\"一句话自我介绍，不超过40字\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">详细自我介绍</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <textarea name=\"siremark\" class=\"form-control\" rows=\"5\" placeholder=\"向支持者详细介绍你自己或你的团队及商品背景，让支持者在最短时间内了解你，不超过160字\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">联系电话</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" name=\"tel\" class=\"form-control\" placeholder=\"此信息不会显示在商品页面\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label class=\"col-sm-2 control-label\">客服电话</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" name=\"cstel\" class=\"form-control\" placeholder=\"此信息显示在商品页面\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"panel-footer\" style=\"text-align:center;\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn  btn-warning btn-lg\" onclick=\"doSubmit()\">提交</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn  btn-warning btn-lg\" onclick=\"window.location.href='index.html'\">取消</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\" style=\"margin-top:20px;\">\r\n");
      out.write("            <div class=\"row clearfix\">\r\n");
      out.write("                <div class=\"col-md-12 column\">\r\n");
      out.write("                    <div id=\"footer\">\r\n");
      out.write("                        <div class=\"footerNav\">\r\n");
      out.write("                             <a rel=\"nofollow\" href=\"http://www.layoutit.cn\">关于我们</a> | <a rel=\"nofollow\" href=\"http://www.layoutit.cn\">服务条款</a> | <a rel=\"nofollow\" href=\"http://www.layoutit.cn\">免责声明</a> | <a rel=\"nofollow\" href=\"http://www.layoutit.cn\">网站地图</a> | <a rel=\"nofollow\" href=\"http://www.layoutit.cn\">联系我们</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"copyRight\">\r\n");
      out.write("                            Copyright ?2017-2017layoutit.cn 版权所有\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("    </div> <!-- /container -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/docs.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/script/back-to-top.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("$('#myTab a').click(function (e) {\r\n");
      out.write("  e.preventDefault()\r\n");
      out.write("  $(this).tab('show')\r\n");
      out.write("})\r\n");
      out.write(" \r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#headerImgBtn\").click(function(){\r\n");
      out.write("\t\tvar fileObj = $(this).next();\r\n");
      out.write("\t\tfileObj.click();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#imgBtn\").click(function(){\r\n");
      out.write("\t\tvar fileObj = $(this).next();\r\n");
      out.write("\t\tfileObj.click();\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("    \r\n");
      out.write("    function doSubmit(){\r\n");
      out.write("\t    $(\"#goodsForm\").submit();\r\n");
      out.write("    }\r\n");
      out.write("\t</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/member/addGoods.jsp(129,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/member/addGoods.jsp(129,15) '${gcs}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${gcs}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/member/addGoods.jsp(129,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("gc");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                  <label class=\"radio-inline\">\r\n");
            out.write("                      <input type=\"radio\" name=\"categoryid\" id=\"categoryid\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gc.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write('"');
            out.write('>');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${gc.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
            out.write("\r\n");
            out.write("                    </label>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
