/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.77
 * Generated at: 2020-03-12 08:23:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <title>欢迎来到超洁洗衣店</title>\r\n");
      out.write("\r\n");
      out.write("        <!-- CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"http://fonts.googleapis.com/css?family=Roboto:400,100,300,500\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/font-awesome/css/font-awesome.min.css\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/form-elements.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("        <!--[if lt IE 9]>\r\n");
      out.write("            <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("            <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Favicon and touch icons -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/icos/favicon.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/icos/apple-touch-icon-144-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/icos/apple-touch-icon-114-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/icos/apple-touch-icon-72-precomposed.png\">\r\n");
      out.write("        <link rel=\"apple-touch-icon-precomposed\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/icos/apple-touch-icon-57-precomposed.png\">\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/imgs/backgrounds/2.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Top menu -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse navbar-no-bg\" role=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#top-navbar-1\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<a class=\"navbar-brand\" href=\"index.html\">超洁洗衣店</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"top-navbar-1\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"li-social\">\r\n");
      out.write("\t\t\t\t\t\t\t    <a href=\"#\"><strong>分享</strong></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-facebook\"></i></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-twitter\"></i></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-envelope\"></i></a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Top content -->\r\n");
      out.write("        <div class=\"top-content\">\r\n");
      out.write("        \t\r\n");
      out.write("            <div class=\"inner-bg\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-7 text\">\r\n");
      out.write("                            <h1><strong>欢迎来到</strong> 超洁洗衣店</h1>\r\n");
      out.write("                            <div class=\"description\">\r\n");
      out.write("                            \t<p>\r\n");
      out.write("\t                            \tThis is a free responsive flat registration form made with Bootstrap. \r\n");
      out.write("\t                            \tDownload it on <a href=\"#\"><strong>AZMIND</strong></a>, customize and use it as you like!\r\n");
      out.write("                            \t</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"top-big-link\">\r\n");
      out.write("                            \t<a class=\"btn btn-link-1\" href=\"#\">Button 1</a>\r\n");
      out.write("                            \t<a class=\"btn btn-link-2\" href=\"#\">Button 2</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-5 form-box\">\r\n");
      out.write("                        \t<div class=\"form-top\">\r\n");
      out.write("                        \t\t<div class=\"form-top-left\">\r\n");
      out.write("                        \t\t\t<h3>立即注册</h3>\r\n");
      out.write("                            \t\t<p>填写下面表单完成注册:</p>\r\n");
      out.write("                        \t\t</div>\r\n");
      out.write("                        \t\t<div class=\"form-top-right\">\r\n");
      out.write("                        \t\t\t<i class=\"fa fa-pencil\"></i>\r\n");
      out.write("                        \t\t</div>\r\n");
      out.write("                        \t\t<div class=\"form-top-divider\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-bottom\">\r\n");
      out.write("\t\t\t                    <form role=\"form\" method=\"post\" action=\"\" class=\"login-form\">\r\n");
      out.write("\t\t\t                    \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                    \t\t<label class=\"sr-only\" for=\"form-first-name\">Loginacct</label>\r\n");
      out.write("\t\t\t                        \t<input type=\"text\" id=\"loginacct\" name=\"form-first-name\" placeholder=\"Loginacct...\" class=\"form-first-name form-control\" id=\"form-first-name\">\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                        <div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<label class=\"sr-only\" for=\"form-last-name\">Memberpswd</label>\r\n");
      out.write("\t\t\t                        \t<input type=\"text\" id=\"memberpswd\" name=\"form-last-name\" placeholder=\"Memberpswd...\" class=\"form-last-name form-control\" id=\"form-last-name\">\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t                        <div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<label class=\"sr-only\" for=\"form-email\">Nickname</label>\r\n");
      out.write("\t\t\t                        \t<input type=\"text\" id=\"nickname\" name=\"form-email\" placeholder=\"Nickname...\" class=\"form-last-name form-control\" id=\"form-email\">\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                        <div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<label class=\"sr-only\" for=\"form-email\">Email</label>\r\n");
      out.write("\t\t\t                        \t<input type=\"text\" id=\"email\" name=\"form-email\" placeholder=\"Email...\" class=\"form-email form-control\" id=\"form-email\">\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                      <a class=\"btn btn-lg btn-success btn-block\" onclick=\"doRegister()\">\r\n");
      out.write("\t\t\t\t\t\t\t立即注册!  </a>\r\n");
      out.write("\t\t\t                  \r\n");
      out.write("\t\t\t                       \r\n");
      out.write("\t\t\t                    </form>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Javascript -->\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/jquery.backstretch.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/assets/js/scripts.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/layer/layer.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("        function doRegister(){\r\n");
      out.write("        \r\n");
      out.write("            var loginacct  = $(\"#loginacct\").val();\r\n");
      out.write("            var memberpswd = $(\"#memberpswd\").val();\r\n");
      out.write("            var nickname   = $(\"#nickname\").val();\r\n");
      out.write("            var email      = $(\"#email\").val();\r\n");
      out.write("            if(loginacct==\"\")\r\n");
      out.write("            {\r\n");
      out.write("           \t //alert(\"输入的账号为空\");\r\n");
      out.write("           \t layer.msg(\"输入的账号为空\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("           \t\t //消息关闭后的逻辑\r\n");
      out.write("           \t });\r\n");
      out.write("           \t return;\r\n");
      out.write("           \t }\r\n");
      out.write("            if(memberpswd==\"\")\r\n");
      out.write("       \t    {\r\n");
      out.write("           \t //alert(\"输入的密码为空\");\r\n");
      out.write("           \t layer.msg(\"输入的密码为空\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("           \t\t //消息关闭后的逻辑\r\n");
      out.write("           \t });\r\n");
      out.write("           \t return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if(nickname==\"\")\r\n");
      out.write("       \t    {\r\n");
      out.write("           \t //alert(\"输入的密码为空\");\r\n");
      out.write("           \t layer.msg(\"输入的昵称为空\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("           \t\t //消息关闭后的逻辑\r\n");
      out.write("           \t });\r\n");
      out.write("           \t return;\r\n");
      out.write("            }\r\n");
      out.write("            if(email==\"\")\r\n");
      out.write("       \t    {\r\n");
      out.write("           \t //alert(\"输入的密码为空\");\r\n");
      out.write("           \t layer.msg(\"输入的邮箱为空\", {time:1500, icon:5, shift:6}, function(){\r\n");
      out.write("           \t\t //消息关闭后的逻辑\r\n");
      out.write("           \t });\r\n");
      out.write("           \t return;\r\n");
      out.write("            }\r\n");
      out.write("         \r\n");
      out.write("            //AJAX执行注册\r\n");
      out.write("            var registerUrl = \"\";\r\n");
      out.write("           \r\n");
      out.write("           \t registerUrl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/member/doAJAXRegister\";\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("             var index=0;\r\n");
      out.write("             $.ajax({\r\n");
      out.write("           \t type : \"POST\",\r\n");
      out.write("           \t url  : registerUrl,\r\n");
      out.write("           \t data : {\r\n");
      out.write("           \t\t \"loginacct\"   : loginacct,\r\n");
      out.write("           \t\t \"memberpswd\"  : memberpswd,\r\n");
      out.write("           \t\t \"nickname\"    : nickname,\r\n");
      out.write("           \t\t \"email\"       : email\r\n");
      out.write("           \t } ,\r\n");
      out.write("            \t beforeSend : function(){\r\n");
      out.write("           \t\t index = layer.load(2, {time: 10*1000});\r\n");
      out.write("           \t\t \r\n");
      out.write("           \t }, \r\n");
      out.write("           \t// alert(\"aaa\");\r\n");
      out.write("           \t success : function(result){\r\n");
      out.write("           \t\t layer.close(index);\r\n");
      out.write("           \t\t if(result.success){\r\n");
      out.write("           \t\t\t \r\n");
      out.write("           \t\t\t layer.msg(\"注册成功,正在为您返回登录页面。\", {time:3000, icon:5, shift:6}, function(){\r\n");
      out.write("                  \t\t //消息关闭后的逻辑\r\n");
      out.write("                  \t });\r\n");
      out.write("           \t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APP_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login\";\r\n");
      out.write("           \t\t } else {\r\n");
      out.write("           \t\t\r\n");
      out.write("           \t\t }\r\n");
      out.write("           \t\t \r\n");
      out.write("           \t }\r\n");
      out.write("            });\r\n");
      out.write("      \r\n");
      out.write("       } \r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <!--[if lt IE 10]>\r\n");
      out.write("            <script src=\"assets/js/placeholder.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
